#!/usr/bin/env python3
# Generate a practice skill draft from mining results

"""
Usage: python3 generate_practice_skill.py <mining_result.json> [--output-dir DIR]

Takes the output of mine_naming.py (or similar mining scripts) and generates
a SKILL.md draft that captures the discovered conventions.

This is the learning loop closure point:
  mine_naming.py → mining_result.json → generate_practice_skill.py → SKILL.md draft

The generated SKILL.md is a DRAFT that should be reviewed by a human before
being added to the skill repository.

Output: SKILL.md content to stdout (or to file if --output-dir specified)
"""

import json
import sys
import os
from datetime import datetime


def generate_skill_content(mining_data):
    """Generate SKILL.md content from mining data."""
    project_root = mining_data.get("project_root", "unknown")
    project_name = os.path.basename(project_root)

    class_suffixes = mining_data.get("class_suffixes", {})
    test_patterns = mining_data.get("test_naming_patterns", {})
    package_layers = mining_data.get("package_layers", {})

    lines = []

    # Frontmatter
    lines.append("---")
    lines.append(f"name: {project_name}-conventions")
    lines.append(f"description: \"Conventions mined from {project_name} codebase — class naming, test patterns, package structure.\"")
    lines.append("tags: [convention, mined, auto-generated]")
    lines.append("version: \"1.0\"")
    lines.append("category: custom")
    lines.append("scope: workspace")
    lines.append(f"note: \"Auto-generated on {datetime.now().strftime('%Y-%m-%d')}. Review before use.\"")
    lines.append("---")
    lines.append("")

    # Title
    lines.append(f"# {project_name} Conventions (Mined)")
    lines.append("")
    lines.append("> **This skill was auto-generated by `convention-miner`. Review and edit before adding to your skill repository.**")
    lines.append("")

    # Class Naming
    if class_suffixes:
        lines.append("## Class Naming Conventions")
        lines.append("")
        lines.append("| Suffix | Count | Implied Pattern |")
        lines.append("|--------|-------|-----------------|")
        for suffix, count in sorted(class_suffixes.items(), key=lambda x: -x[1]):
            lines.append(f"| `{suffix}` | {count} | Classes ending with `{suffix}` follow the {suffix} pattern |")
        lines.append("")

    # Test Naming
    if test_patterns:
        lines.append("## Test Naming Conventions")
        lines.append("")
        dominant = max(test_patterns, key=test_patterns.get)
        lines.append(f"**Dominant pattern**: `{dominant}` ({test_patterns[dominant]} occurrences)")
        lines.append("")
        lines.append("| Pattern | Count |")
        lines.append("|---------|-------|")
        for pattern, count in sorted(test_patterns.items(), key=lambda x: -x[1]):
            lines.append(f"| `{pattern}` | {count} |")
        lines.append("")

    # Package Structure
    if package_layers:
        lines.append("## Package Layers")
        lines.append("")
        lines.append("| Layer | Usage Count |")
        lines.append("|-------|-------------|")
        for layer, count in sorted(package_layers.items(), key=lambda x: -x[1]):
            lines.append(f"| `{layer}` | {count} |")
        lines.append("")

    # Statistics
    lines.append("## Mining Statistics")
    lines.append("")
    lines.append(f"- Classes scanned: {mining_data.get('class_count', 'N/A')}")
    lines.append(f"- Methods scanned: {mining_data.get('method_count', 'N/A')}")
    lines.append(f"- Test functions scanned: {mining_data.get('test_count', 'N/A')}")
    lines.append(f"- Mining date: {datetime.now().strftime('%Y-%m-%d')}")
    lines.append("")

    return "\n".join(lines)


def main():
    import argparse
    parser = argparse.ArgumentParser(description="Generate practice skill from mining results")
    parser.add_argument("input_file", help="JSON file from mine_naming.py")
    parser.add_argument("--output-dir", help="Directory to write SKILL.md to")
    args = parser.parse_args()

    try:
        with open(args.input_file, "r") as f:
            mining_data = json.load(f)
    except (json.JSONDecodeError, IOError) as e:
        print(f"Error reading input file: {e}", file=sys.stderr)
        sys.exit(1)

    content = generate_skill_content(mining_data)

    if args.output_dir:
        os.makedirs(args.output_dir, exist_ok=True)
        output_path = os.path.join(args.output_dir, "SKILL.md")
        with open(output_path, "w") as f:
            f.write(content)
        print(f"Skill draft written to: {output_path}")
    else:
        print(content)


if __name__ == "__main__":
    main()
